### PR TITLE
allowing arquillian container to wait for sometime

### LINKED ISSUE #37: CDI TCK test(testSessionContextActiveOnStartAsync) is failing.
While running CDI 2.0 TCK in GlassFish (Weld 3.0.0.Final) Following test is failing

testSessionContextActiveOnStartAsync(org.jboss.cdi.tck.tests.context.session.async.SessionContextAsyncListenerTest): 500 Internal Server Error for http://localhost:8080/12e3cd06754c1b9f72abe8f0c31ecb930cd13/AsyncServlet?test=loop

### PR DESCRIPTION
**Pull request by ankathur**
It seems arquillian conatiner is looking for glassfish even before glassfish has started properly. 
So adding some wait time to resolve the issue.

Fixes #37

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thank you very much for your pull request. I would like to suggest following improvements:

  * let's make timeout set by default to 5s but configurable through `arquillian.xml` see [configuration class](https://github.com/arquillian/arquillian-container-glassfish/blob/0699fef522e149434191761c5f8bf0be6d533db1/glassfish-common/src/main/java/org/jboss/arquillian/container/glassfish/CommonGlassFishConfiguration.java) for details
  * we can also define polling to detect availability of the server even faster. This again can be for example fixed to `100ms` and configurable through `arquillian.xml`.

Both of configurable values can be miliseconds for the time being.

This way we can fine tune waiting time and do not wait unnecessarily long during test execution.

**Comment by ankathur** [comment]
Thanks for your input. I do feel this should be configurable. I will update the pull request.

**Comment by ankathur** [comment]
Please review the updated PR.

**Comment by jjsnyder** [comment]
@bartoszmajsak, Can you merge @ankathur's changes if you approve of them?  We would like to setup nightly runs of the tck and are waiting for the changes to be public.
JJ

**Comment by bartoszmajsak** [comment]
Sure, I fixed two minor things

  * Code formatting
  * Renamed properties
    * `waitTime` -> `waitTimeMs`
    * `polling` -> `retries`

**Comment by bartoszmajsak** [comment]
Pushed upstream 389a4d99f42d629a6cc03276d43fe37341c0d3f9

Thanks for your contribution.

**Comment by bartoszmajsak** [comment]
New version has been released. It will take a bit to land it in central, but normally less than a day. Please note that we are gradually switching to widely known semantic versioning scheme - which means we are dropping `.Final` suffix (we were semantic before too, but we decided to follow well known convention)

New version is `1.0.1`.

**Comment by jjsnyder** [comment]
Ok, I'll keep an eye out for it.  Thank you!

**Pull request closed without merging**
