### PR TITLE
Support for Glassfish 4.x and logging to IDE console

### PR DESCRIPTION
**Pull request by dadrus**
Since I renamed the remote branch, leading to a removal of the old branch, the initial pull request was closed. Because of this I reopen the same request but based on the new branch name.

Based on the implementation of glassfish-managed-3.1, this pull request contains the implementation to support managed glassfish4. the main differences are:
- the `--verbose` flag (which seems to be new in glassfish4) is added to the command line to start-domain
- the `start-domain` process is started in the background to be able to grap the output and redirect it to the console. This way if the `outputToConsole` is set to `true`, the server logging goes to the IDE console as well.
- to avoid long start up waiting times until the glassfish is started, a new configuration property `startupTimeoutInSeconds` was added. The default value is 120.
- All tests from glassfish-managed-3.1 were adapted. The difference here is, that the deployments have unique names. during my test runs I've encountered situations with stale data in glassfish and have had to delete the contents of _applications_ and _generated_ folders before the tests went green again.

I assume the people would like to see the log always in the console, so maybe `outputToConsole` should be set to true by default.

I've tried the same implementation with glassfish3 and it did not work. Because of this, the pull request contains the new glassfish-managed-4 project (it works with all 4.x versions of glassfish).

I've also checked wether the 370b468 commit solves the stale files issue, which sometimes happen. Unfortunately it does not.

Regards,
Dimitrij

### CODE REVIEW

**Comment by aslakknutsen** [comment]
The 3.1 impl work with 4.1. So the new thing here that require a new adaptor is the --verbose/console log. Am I getting this correct?

**Comment by dadrus** [comment]
Hi,
Yes, the 3.1 impl works with 4.x. But there is no way to get the console output of the server to the console of the test runner with the 3.1 impl. To see what is going on, one have to `tail` the log of the glassfish. The `--verbose` flag can be used to achieve this. Even the v3.x version of glassfish documents this flag, I was not able to make use of it with glassfish 3.x using the supposed implementation. It works however with 4.x like a charm. And this is the reason for the new adapter.
Maybe one have to do something in addition to get the desired results with glasfish 3.x as well.

**Comment by dadrus** [comment]
Hello Aslak,

Have you had any time to look at the pull request? What do you think about it? Is there something open from your point of view before it can be integrated into the mainstream?

Regards,
Dimitrij

**Comment by bartoszmajsak** [comment]
I think we can simply bring these changes to already existing code base. If it does not work like it should for GF 3.1, but exactly the same code works for newer versions we can hint in the documentation. I will take care of code adjustments for now. Please let me know if there is something else which would opt for having new module `-4.x`.

**Comment by dadrus** [comment]
Hello Bartosz,
There is still the issue with stale files which sometime remain (see my initial comment) also with the 3.x adapter. I did not had time however to take a deeper look at it.

Regards,
Dimitrij

**Pull request closed without merging**
